services:
  app:
    image: rijalanupraj/mooc-fi-chapter4-security-and-optimization-1-express
    ports:
      - 8080:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: app

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
      - WATCHTOWER_LABEL_ENABLE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
